version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./fastuga-backend/application/:/var/www/laravel-backend/
      - ./fastuga-backend/logs/nginx:/var/log/nginx/
    container_name: nginx
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: fastuga-backend/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./fastuga-backend/application/:/var/www/laravel-backend/
      - ./fastuga-backend/logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}

      LOG_CHANNEL: ${LOG_CHANNEL}

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_CONNECTION}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - "9000"
    command: >
      bash -c "chmod +x /var/www/laravel-backend/laravel_setup.sh && /var/www/laravel-backend/laravel_setup.sh"

  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./fastuga-backend/db-data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysql --user=${DB_USERNAME} --password=${DB_PASSWORD} -e "SELECT SCHEMA_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = ''${DB_DATABASE}''" | grep ${DB_DATABASE}',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  internal:
    driver: bridge
